Harden pgfmathparser against active chars
pgf-tikz/pgf pull request #1221
Opened 2022-11-30 06:13 UTC by josephwright

In general, the grabbed token could always be active, so precautions are needed. Here, the places that the grabbed token is tested and those where it's used in a csname are addressed. The tests need \noexpand, the csname usage \string, with appropriate expansion.

2022-11-30 09:57 UTC, hmenke commented
Looks good, thanks! Could you please add a few tests?

2022-11-30 09:59 UTC, josephwright commented
> Looks good, thanks! Could you please add a few tests?

I'll work on it: the tests I have locally also depend on another patch that's a bit harder to articulate just yet. Later today ...

2022-12-01 00:00 UTC, muzimuzhi requested changes

2022-12-01 00:00 UTC, muzimuzhi commented on tex/generic/pgf/math/pgfmathparser.code.tex
> +            \expandafter\ifx\csname pgfmath@base@\expandafter\pgfmath@number\expandafter\string\pgfmath@token\endcsname\relax%
```suggestion
            \expandafter\ifx\csname pgfmath@base@\pgfmath@number\expandafter\string\pgfmath@token\endcsname\relax%
```
It seems the first added `\expandafter` is unnecessary.

2022-12-01 00:00 UTC, muzimuzhi commented on tex/generic/pgf/math/pgfmathparser.code.tex
> +                \csname pgfmath@base@\expandafter\pgfmath@number\expandafter\string\pgfmath@token\endcsname%
```suggestion
                \csname pgfmath@base@\pgfmath@number\expandafter\string\pgfmath@token\endcsname%
```

2023-10-23 07:12 UTC, hmenke approved these changes

2023-10-23 07:12 UTC, merged