Fixing typos
pgf-tikz/pgf pull request #1252
Opened 2023-04-04 10:21 UTC by deining

This PR fixes various typos I spotted in the documentation and in the source code.

- [x] Code changes are licensed under [GPLv2][GPL] + [LPPLv1.3c][LPPL]
- [x] Documentation changes are licensed under [FDLv1.2][FDL]

2023-04-04 20:20 UTC, muzimuzhi reviewed
Also I'm not sure about the necessity of change "arithmetics function" -> "arithmetic function". Yes the latter is more common...

2023-04-04 20:20 UTC, muzimuzhi commented on doc/generic/pgf/pgfmanual-en-guidelines.tex
> +    \item Background images and shadings distract and only seldom add
doubtful, or seems unnecessary. According to Merriam-Webster [\[1\]][1],

> _Seldomly_ is a perfectly logical adverb form, but it has been labeled “archaic” or “rare” in our dictionaries for over a century (our 19th-century editions didn’t even enter it). Seldom is itself an adverb (“We seldom go out on weeknights”), making the _-ly_ form redundant and unnecessary. It has been out of standard use for so long that it is rarely encountered in publications with national readership, but it still sometimes pops up:
> 
> > And there are the requisite pool and tennis court, which are seldomly used.
> > —The New York Times, 6 July 1997
> > 
> > Apple is wise enough to introduce new colours so seldomly that fans go into meltdown each time a new hue is inducted into the fold.
> > —The Telegraph, 22 September 2015

[1]: https://www.merriam-webster.com/words-at-play/6-common-hypercorrections-and-how-to-avoid-them

2023-04-04 20:20 UTC, muzimuzhi commented on doc/generic/pgf/pgfmanual-en-tikz-shapes.tex
> +path has been drawn} or (more seldom and only if you add the |behind path|
ditto

2023-04-04 20:20 UTC, muzimuzhi commented on doc/generic/pgf/CHANGELOG.md
If I remembered right, there was a policy (@hmenke) to not alter existing `CHANGELOG.md` entries only for typo corrections, but I can't find the source right now.

2023-04-05 11:13 UTC, deining commented on doc/generic/pgf/pgfmanual-en-guidelines.tex
> +    \item Background images and shadings distract and only seldom add
I agree (and already was aware of the fact) that `seldomly` is not wrong per se.
My motivation: if you search for `seldom` in the whole repo, you get
- `seldom`: 4 times
- `seldomly`: 3 times

I think we should harmonize that, and I opted for the more often used expression `seldom`. However, I will happily change back to `seldomly`, if wanted. Please advise what to do here, I will happily put in place whatever solution you come up with.

2023-04-05 11:13 UTC, deining commented on doc/generic/pgf/pgfmanual-en-tikz-shapes.tex
> +path has been drawn} or (more seldom and only if you add the |behind path|
See above.

2023-04-05 11:14 UTC, deining commented on doc/generic/pgf/CHANGELOG.md
The same here. I think, that correcting typos here makes sense, but I revert these changes if you opt for this. Please advise what to do here.

2023-04-05 11:19 UTC, hmenke commented on doc/generic/pgf/CHANGELOG.md
The thing is, that by correcting typos in `CHANGLOG.md`, you are not actually correcting anything, because the changelog has also been published in GitHub releases, the mailing list, CTAN, etc. which are not updated by fixing this file. Therefore any effort expended on polishing changelog entries that have already appeared in published releases is wasted and pointless.

2023-04-13 07:31 UTC, hmenke requested changes
This looks pretty good. Could you please revert your changes to `CHANGELOG.md` (see my previous comment for reasoning) and incorporate #1253 into this PR?

2023-04-13 09:45 UTC, deining commented
> Could you please revert your changes to `CHANGELOG.md`

Reverted as requested.

> and incorporate #1253 into this PR?

Done.

Looking forward seeing this merged. Thanks!

2023-04-13 10:43 UTC, merged