pgfkeys: fix two handler problems
pgf-tikz/pgf pull request #913
Opened 2020-08-29 03:42 UTC by muzimuzhi

See commit messages and comments under corresponding issues for more info.

Close #654
Close #912

2020-08-29 04:04 UTC, hmenke requested changes
Please revert the whitespace-only changes.  I don't care about “consistency”, I want a minimal diff.

2020-08-29 04:24 UTC, muzimuzhi commented
> Please revert the whitespace-only changes. I don't care about “consistency”, I want a minimal diff.

That's not for consistency, but for readability. I can live with in-consistency in the code base and I will not add as many as whitespace-only changes just for “consistency”.

But from my point of view, https://github.com/pgf-tikz/pgf/pull/913/commits/1b420435c47883620ede1156e56005275d73561f do makes reading and understanding implementation of `.add code` easier.

2020-08-29 04:26 UTC, muzimuzhi commented on tex/generic/pgf/utilities/pgfkeys.code.tex
>    }%
For example, before that commit, it's hard to identify which `}` ends the second argument of `\pgfkeysifdefined`.

2020-08-29 05:49 UTC, hmenke commented
Merged in https://github.com/pgf-tikz/pgf/commit/ab25066f631cd8137a4b7c91aef4b0ccfc97f991

2020-08-29 05:49 UTC, closed without merging

2020-08-29 14:51 UTC, muzimuzhi commented
I respect your decision, though ... .

Avoiding whitespace-only changes like tab-to-space replacement is reasonable, but avoiding every such change is not always good, I'm afraid. For example, when the definition is long and complex, changing
```tex
\def\cmd{%
<definition>
}
```
to
```tex
\def\cmd{%
<definition>
}
```
helps everyone who reads the code in the future. Utilities are for users, while code is written and maintained for people to read.

I'm not expecting to influence your decision, but restate my idea with an example. If anything looks offending, that's all my fault (maybe partly the fault of my influent hence sometimes unconsciously impolite English).

2020-08-30 19:26 UTC, muzimuzhi commented
I was convinced. unnecessary changes made the tracing work harder. For large repo with long history and perhaps in-sufficient maintenance support, please the one who traces problems is more important than improve code consistency and/or readability. For example, the change history of [`\pgfpointintersectionoflines`](https://github.com/pgf-tikz/pgf/blame/f5ee9149477346a61949b6f1bc81757a7ebc9da8/tex/generic/pgf/basiclayer/pgfcorepoints.code.tex#L197).